import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./Providers";
import Navbar from "@/components/Navbar";
import PurchaseCard from "@/components/PurchaseCard";
import AboutArtist from "@/components/AboutArtist";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <div className="min-h-screen flex flex-col">
            <Navbar />
            <main className="py-8 flex-grow">
              <div className="max-w-8xl mx-auto px-4">
                <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
                  <div className="lg:col-span-8">{children}</div>
                  <div className="hidden lg:block lg:col-span-4">
                    <PurchaseCard />
                    <AboutArtist />
                  </div>
                </div>
              </div>
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
